# Some constants
NULL_BABELNET_ID = "NULL_BID"
NULL_TYPE = "NULL_T"
CUSTOM_TYPE = "CUSTOM_TYPE"

# XML tags
DISAMBIGUATED_ARTICLE_TAG = "disambiguatedArticle"
TEXT_TAG = "text"
ANNOTATIONS_TAG= "annotations"
ANNOTATION_TAG= "annotation"

BABELNET_ID_TAG = "babelNetID"
MENTION_TAG = "mention"
ANCHOR_START_TAG= "anchorStart"
ANCHOR_END_TAG = "anchorEnd"
TYPE_TAG = "type"


TEXT_TAG_IDX = 0
ANNOTATIONS_TAG_IDX = 1

ANNOTATION_TYPE_MSC = "MSC"
ANNOTATION_TYPE_HL = "HL"
ANNOTATION_TYPE_BABELFY = "BABELFY"

ANNOTATION_BABELNETID_TAG_POS = 0
ANNOTATION_MENTION_POS = 1
ANNOTATION_ANCHORSTART_POS = 2
ANNOTATION_ANCHOREND_POS = 3
ANNOTATION_TYPE_TAG_POS = 4


# POS tags
VERB_POSTAG = "VERB"
PROPN_POSTAG = "PROPN"
PRON_POSTAG = "PRON"
NOUN_POSTAG = "NOUN"

# dep tags
NSUBJ_DEPTAG = "nsubj"
NSUBJPASS_DEPTAG = "nsubjpass"
POBJ_DEPTAG = "pobj"
COBJ_DEPTAG = "cobj"
DOBJ_DEPTAG = "dobj"
ATTR_DEPTAG = "attr"

SPECIAL_DEP_TAGS = [NSUBJ_DEPTAG, NSUBJPASS_DEPTAG, POBJ_DEPTAG, ATTR_DEPTAG, COBJ_DEPTAG, DOBJ_DEPTAG]
SUBJ_DEPTAGS = [NSUBJ_DEPTAG, NSUBJPASS_DEPTAG]
OBJ_DEPTAGS = [POBJ_DEPTAG, ATTR_DEPTAG, COBJ_DEPTAG, DOBJ_DEPTAG]